dataset:
  train:
    class: ConcatDatasetWrapper
    datasets:
      - class: PeptideDatasetPrompt
        mmap_dir: ./datasets/peptide/pepbench/processed
        specify_index: ./datasets/peptide/pepbench/processed/train_index.txt
        cluster: ./datasets/peptide/pepbench/train.cluster
      - class: PeptideDatasetPrompt
        mmap_dir: ./datasets/peptide/pepbench/processed
        specify_index: ./datasets/peptide/pepbench/processed/non_standard_index.txt
      - class: PeptideDatasetPrompt
        mmap_dir: ./datasets/peptide/ProtFrag/processed

      - class: AntibodyDatasetPrompt
        mmap_dir: ./datasets/antibody/SAbDab/processed
        specify_index: ./datasets/antibody/SAbDab/processed/train_index.txt
        test_mode: true

  valid:
    class: ConcatDatasetWrapper
    datasets:
      - class: PeptideDatasetPrompt
        mmap_dir: ./datasets/peptide/pepbench/processed
        specify_index: ./datasets/peptide/pepbench/processed/valid_index.txt

      - class: AntibodyDatasetPrompt
        mmap_dir: ./datasets/antibody/SAbDab/processed
        specify_index: ./datasets/antibody/SAbDab/processed/valid_index.txt
        test_mode: true

  test:
    class: ConcatDatasetWrapper
    datasets:
      - class: PeptideDatasetPrompt
        mmap_dir: ./datasets/peptide/LNR/processed

      - class: AntibodyDatasetPrompt
        mmap_dir: ./datasets/antibody/SAbDab/processed
        specify_index: ./datasets/antibody/SAbDab/processed/test_index.txt
        test_mode: true
dataloader:
  train:
    shuffle: true
    num_workers: 16
    batch_size: 4
  valid:
    num_workers: 8
    batch_size: 4

